### ISSUE TITLE
no version with ember-cli 2.16.0 and EMBER_ENV=production

### ISSUE THREAD

**Issue by RichardJohnn** [ember-cli/ember-cli-app-version#52]
after updating from ember-cli 2.15.3 to 2.16.0, the version isn't picked up when EMBER_ENV=production is set

**Comment by KeithClinard** [comment]
I had the same issue.
In my case it was due to using git tags without using a package.json version.

Support for git tags without package versions was recently removed from `git-repo-version`.
This appears to have been unintentional, so I have created a pull request to reintroduce this functionality.
https://github.com/cibernox/git-repo-version/pull/20

In the mean time, fixing your version of ember-cli-app-version to `3.1.0` will resolve the issue.

**Comment by KeithClinard** [comment]
Well that was fast.
My PR has been merged and a new version of `git-repo-version` has been tagged.

Can you reinstall and test this again? (Your lockfile may need to be regenerated)
